### *arguemnts 是參數識別字前加上一個星號，當成一組tuple
### **keywords 是參數識別字前加上兩個星號，當成一組dict

In [ ]:
def function_name(*arguments, *keywords*):
    # do something
    return something

## 更多NumPy建立array的方式

In [2]:
import numpy as np

a = np.arange(5)
print(a)
b = np.arange(1, 5, 4)
print(b)

[0 1 2 3 4]
[1]


In [4]:
c = np.zeros(2)
print(c)
d = np.zeros((2, 2))
print(d)

[0. 0.]
[[0. 0.]
 [0. 0.]]


In [5]:
e = np.ones(2)
print(e)
f = np.ones((2, 2))
print(f)

[1. 1.]
[[1. 1.]
 [1. 1.]]


## array維度轉換

In [6]:
a = np.arange(16)
print(a)
b = a.reshape((4, 4))
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


## 向量長度計算


#### 使用numpy的linalg模組的norm方法

In [5]:
import numpy as np

park = np.array([1, 2])
norm_park = np.linalg.norm(park)
print(norm_park)

2.23606797749979


In [2]:
import numpy as np

In [6]:
park = np.array([1, 2])
norm_park = np.linalg.norm(park)
print(norm_park)

2.23606797749979


In [7]:
office = np.array([4, 4])
park_office = park - office
norm = np.linalg.norm(park_office)
print(norm)

3.605551275463989


#### 切割運算子, array[start: end: step]

In [9]:
a = np.arange(10)
print(a)

b = a[2: 9: 3]
c = a[::2]
d = a[::-1]
print(b)
print(c)
print(d)

[0 1 2 3 4 5 6 7 8 9]
[2 5 8]
[0 2 4 6 8]
[9 8 7 6 5 4 3 2 1 0]


## 矩陣運算


#### 矩陣與純量的四則運算

In [12]:
a = np.array([[1, 2, 3], [4, 5, 6]])
s = 5

b = a - s
print(b)
c = a + s
print(c)
d = a * s
print(d)
e = a / s
print(e)

[[-4 -3 -2]
 [-1  0  1]]
[[ 6  7  8]
 [ 9 10 11]]
[[ 5 10 15]
 [20 25 30]]
[[0.2 0.4 0.6]
 [0.8 1.  1.2]]


#### 點積運算(Dot Product)

In [14]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

z = x.dot(y)
print(z)

[[19 22]
 [43 50]]


## 切割二維元素

In [16]:
a = np.arange(11, 36)

b = a.reshape(5, 5)
print(b)

[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]]


In [19]:
c = b[1, 1:4]
print(c)

d = b[1:3, 0]
print(d)

e = b[::2, ::2]
print(e)

[17 18 19]
[16 21]
[[11 13 15]
 [21 23 25]
 [31 33 35]]


### boolean array

In [23]:
b = np.arange(1, 7)
print(b)
mask = (b % 2 == 0)
print(mask)

[1 2 3 4 5 6]
[False  True False  True False  True]


## 陣列形狀與內容操作

#### 陣列平坦化: 可以將二維陣列變成一維, 方法: ravel

In [25]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
b = a.ravel()
print(b)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


#### 交換陣列維度: T or transpose

In [26]:
a = np.array([[1, 2], [3, 4], [5, 6]])
print(a)
b = a.T
print(b)
c = a.transpose()
print(c)

[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]
[[1 3 5]
 [2 4 6]]


### 內容操作： copy、fill、concatenate
#### 盡量不要用賦值(=)的方式，用copy，不然兩個變數會一起變動

In [3]:
a = np.array([1, 2, 3])
b = a.copy()
print(b)

[1 2 3]


#### fill: 變成單一值

In [8]:
b.fill(5)
print(b)

[5 5 5]


#### concatenate: 合併 參數 axis 預設為 0 直向合併

In [13]:
c = np.concatenate((a, b))
print(c)

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
c = np.concatenate((a, b), axis=0)
print(c)
d = np.concatenate((a, b), axis=1)
print(d)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
